GET https://www.w3.org/People/Berners-Lee/
###

GET https://rickandmortyapi.com/api/character
###

GET https://rickandmortyapi.com/api/character/1,2
###

GET https://pokeapi.co/api/v2/pokemon/charizard
###

GET https://pokeapi.co/api/v2/berry/
###


// API's Publicas

// CAT Facts
GET https://cat-fact.herokuapp.com/facts
###

// HTTP.dog
GET https://http.dog/100.jpg
###

GET https://http.dog/460.jpg
###